[env]
  TERM = "xterm-256color"

#startup modes:Windowed, Maximized, Fullscreen
[window]
  padding = { x = 2, y = 2 }
  dynamic_padding = true
  opacity = 0.8
  title = "Alacritty"
  startup_mode = "Maximized"
  decorations = "buttonless"
  # MacOS binding of Option key to Meta
  option_as_alt = "Both"

# Note on MacOS the font rendering is 'thicker' than, say, iTerm2, to fix:
# run 'defaults write org.alacritty AppleFontSmoothing -int 0' and logout/login
[font]
  size = 11.75
  [font.normal] 
    family = "JetBrainsMono Nerd Font"
  [font.bold]
    # family = "JetBrainsMono Nerd Font"
  [font.italic] 
    # family = "JetBrainsMono Nerd Font"

[mouse]
  hide_when_typing = true

# -------- Colors --------
# --------------------------------------------------------------------------------
# (Catppuccin - frappe) hardcoded
# --------------------------------------------------------------------------------
# Default colors
[colors.primary]
background = '#303446' # base
foreground = '#C6D0F5' # text
# Bright and dim foreground colors
dim_foreground = '#C6D0F5' # text
bright_foreground = '#C6D0F5' # text

# Cursor colors
[colors.cursor]
text = '#303446' # base
cursor = '#F2D5CF' # rosewater

[colors.vi_mode_cursor]
text = '#303446' # base
cursor = '#BABBF1' # lavender

# Search colors
[colors.search.matches]
foreground = '#303446' # base
background = '#A5ADCE' # subtext0
[colors.search.focused_match]
foreground = '#303446' # base
background = '#A6D189' # green
[colors.footer_bar]
foreground = '#303446' # base
background = '#A5ADCE' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#303446' # base
background = '#E5C890' # yellow
[colors.hints.end]
foreground = '#303446' # base
background = '#A5ADCE' # subtext0

# Selection colors
[colors.selection]
text = '#303446' # base
background = '#F2D5CF' # rosewater

# Normal colors
[colors.normal]
black = '#51576D' # surface1
red = '#E78284' # red
green = '#A6D189' # green
yellow = '#E5C890' # yellow
blue = '#8CAAEE' # blue
magenta = '#F4B8E4' # pink
cyan = '#81C8BE' # teal
white = '#B5BFE2' # subtext1

# Bright colors
[colors.bright]
black = '#626880' # surface2
red = '#E78284' # red
green = '#A6D189' # green
yellow = '#E5C890' # yellow
blue = '#8CAAEE' # blue
magenta = '#F4B8E4' # pink
cyan = '#81C8BE' # teal
white = '#A5ADCE' # subtext0

# Dim colors
[colors.dim]
black = '#51576D' # surface1
red = '#E78284' # red
green = '#A6D189' # green
yellow = '#E5C890' # yellow
blue = '#8CAAEE' # blue
magenta = '#F4B8E4' # pink
cyan = '#81C8BE' # teal
white = '#B5BFE2' # subtext1

# Catppuccin End
# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# (Gruvbox dark) hardcoded
# --------------------------------------------------------------------------------
# # Default colors
# [colors.primary]
# # hard contrast background = = '#1d2021'
# background = '#282828'
# # soft contrast background = = '#32302f'
# foreground = '#ebdbb2'

# # Normal colors
# [colors.normal]
# black   = '#282828'
# red     = '#cc241d'
# green   = '#98971a'
# yellow  = '#d79921'
# blue    = '#458588'
# magenta = '#b16286'
# cyan    = '#689d6a'
# white   = '#a89984'

# # Bright colors
# [colors.bright]
# black   = '#928374'
# red     = '#fb4934'
# green   = '#b8bb26'
# yellow  = '#fabd2f'
# blue    = '#83a598'
# magenta = '#d3869b'
# cyan    = '#8ec07c'
# white   = '#ebdbb2'

# Gruvbox End
# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# Key bindings - OFF No need for these due to TMUX and VIM
# --------------------------------------------------------------------------------
[keyboard]
bindings = [
# scrollback
 { key = "PageUp",   mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
 { key = "PageDown", mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
 { key = "Home",     mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
 { key = "End",      mods = "Shift",         mode = "~Alt",        action = "ReceiveChar" },
 { key = "K",        mods = "Command",       mode = "Vi|~Search",  action = "ReceiveChar" },
# # searching
 { key = "F",        mods = "Control|Shift", mode = "~Search",     action = "ReceiveChar" },
 { key = "F",        mods = "Command",       mode = "~Search",     action = "ReceiveChar" },
 { key = "B",        mods = "Control|Shift", mode = "~Search",     action = "ReceiveChar" },
 { key = "B",        mods = "Command",       mode = "~Search",     action = "ReceiveChar" },
# # copy/paste - retain default behavior
 # { key = "Paste",                                                  action = "ReceiveChar" },
 # { key = "Copy",                                                   action = "ReceiveChar" },
 # { key = "V",        mods = "Control|Shift", mode = "~Vi",         action = "ReceiveChar" },
 # { key = "V",        mods = "Command",                             action = "ReceiveChar" },
 # { key = "C",        mods = "Control|Shift",                       action = "ReceiveChar" },
 # { key = "C",        mods = "Command",                             action = "ReceiveChar" },
 # { key = "C",        mods = "Control|Shift", mode = "Vi|~Search",  action = "ReceiveChar" },
 # { key = "C",        mods = "Command",       mode = "Vi|~Search",  action = "ReceiveChar" },
 # { key = "Insert",   mods = "Shift",                               action = "ReceiveChar" },
]
