[env]
  TERM = "xterm-256color"

#startup modes:Windowed, Maximized, Fullscreen
[window]
  padding = { x = 2, y = 2 }
  dynamic_padding = true
  opacity = 0.8
  title = "Alacritty"
  startup_mode = "Maximized"
  decorations = "buttonless"
  # MacOS binding of Option key to Meta
  option_as_alt = "Both"

# Note on MacOS the font rendering is 'thicker' than, say, iTerm2, to fix:
# run 'defaults write org.alacritty AppleFontSmoothing -int 0' and logout/login
[font]
  size = 11.75
  # Note: FiraCode does not have bold or italic, so we use JetBrainsMono for those
  [font.normal] 
    family = "FiraCode Nerd Font Mono"
    # family = "JetBrainsMono Nerd Font"
    style = "Regular"
  [font.bold]
    # family = "FiraCode Nerd Font Mono"
    family = "JetBrainsMono Nerd Font"
  [font.italic] 
    family = "JetBrainsMono Nerd Font"

[mouse]
  hide_when_typing = true

# Colors (Gruvbox dark)
# hardcoding rather than using the gruvbox theme file

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

# End
